name: coco
num_joints: 17
num_channels: 2
coordinate_system: xy
center_joint: 0
num_persons: 1

joint_names:
  - nose            # 0
  - left_eye        # 1
  - right_eye       # 2
  - left_ear        # 3
  - right_ear       # 4
  - left_shoulder   # 5
  - right_shoulder  # 6
  - left_elbow      # 7
  - right_elbow     # 8
  - left_wrist      # 9
  - right_wrist     # 10
  - left_hip        # 11
  - right_hip       # 12
  - left_knee       # 13
  - right_knee      # 14
  - left_ankle      # 15
  - right_ankle     # 16

joint_parents: [-1, 0, 0, 1, 2, 0, 0, 5, 6, 7, 8, 5, 6, 11, 12, 13, 14]

edges:
  - [0, 1]
  - [0, 2]
  - [1, 3]
  - [2, 4]
  - [5, 6]
  - [5, 11]
  - [6, 12]
  - [11, 12]
  - [5, 7]
  - [7, 9]
  - [6, 8]
  - [8, 10]
  - [11, 13]
  - [13, 15]
  - [12, 14]
  - [14, 16]

symmetric_pairs:
  - [1, 2]
  - [3, 4]
  - [5, 6]
  - [7, 8]
  - [9, 10]
  - [11, 12]
  - [13, 14]
  - [15, 16]

body_parts:
  head: [0, 1, 2, 3, 4]
  torso: [5, 6, 11, 12]
  left_arm: [5, 7, 9]
  right_arm: [6, 8, 10]
  left_leg: [11, 13, 15]
  right_leg: [12, 14, 16]
