name: dlc_quadruped
num_joints: 39
num_channels: 2
coordinate_system: xy
center_joint: 15  # neck_base
num_persons: 1

joint_names:
  - nose               # 0
  - upper_jaw          # 1
  - lower_jaw          # 2
  - mouth_end_right    # 3
  - mouth_end_left     # 4
  - right_eye          # 5
  - right_earbase      # 6
  - right_earend       # 7
  - right_antler_base  # 8
  - right_antler_end   # 9
  - left_eye           # 10
  - left_earbase       # 11
  - left_earend        # 12
  - left_antler_base   # 13
  - left_antler_end    # 14
  - neck_base          # 15
  - neck_end           # 16
  - throat_base        # 17
  - throat_end         # 18
  - back_base          # 19
  - back_end           # 20
  - back_middle        # 21
  - tail_base          # 22
  - tail_end           # 23
  - tail_middle        # 24
  - left_front_hoof    # 25
  - left_front_knee    # 26
  - left_front_paw     # 27
  - left_front_elbow   # 28
  - right_front_hoof   # 29
  - right_front_knee   # 30
  - right_front_paw    # 31
  - right_front_elbow  # 32
  - left_back_hoof     # 33
  - left_back_knee     # 34
  - left_back_paw      # 35
  - left_back_elbow    # 36
  - right_back_hoof    # 37
  - right_back_knee    # 38

joint_parents: [15, 0, 0, 0, 0, 0, 5, 6, 6, 8, 0, 10, 11, 11, 13, -1, 15, 16, 17, 15, 19, 19, 20, 22, 22, 28, 28, 26, 15, 32, 32, 30, 15, 36, 36, 34, 20, 20, 20]

edges:
  - [15, 0]
  - [0, 1]
  - [0, 2]
  - [0, 3]
  - [0, 4]
  - [0, 5]
  - [5, 6]
  - [6, 7]
  - [6, 8]
  - [8, 9]
  - [0, 10]
  - [10, 11]
  - [11, 12]
  - [11, 13]
  - [13, 14]
  - [15, 16]
  - [16, 17]
  - [17, 18]
  - [15, 19]
  - [19, 21]
  - [19, 20]
  - [20, 22]
  - [22, 23]
  - [22, 24]
  - [15, 28]
  - [28, 26]
  - [26, 27]
  - [28, 25]
  - [15, 32]
  - [32, 30]
  - [30, 31]
  - [32, 29]
  - [20, 36]
  - [36, 34]
  - [34, 35]
  - [36, 33]
  - [20, 38]
  - [38, 37]

symmetric_pairs:
  - [5, 10]
  - [6, 11]
  - [7, 12]
  - [8, 13]
  - [9, 14]
  - [3, 4]
  - [25, 29]
  - [26, 30]
  - [27, 31]
  - [28, 32]
  - [33, 37]
  - [34, 38]

body_parts:
  head: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]
  neck: [15, 16, 17, 18]
  back: [19, 20, 21]
  tail: [22, 23, 24]
  left_front_leg: [25, 26, 27, 28]
  right_front_leg: [29, 30, 31, 32]
  left_back_leg: [33, 34, 35, 36]
  right_back_leg: [37, 38]

presets:
  standard:
    - nose
    - right_eye
    - left_eye
    - right_earbase
    - left_earbase
    - neck_base
    - back_base
    - back_end
    - tail_base
    - left_front_paw
    - right_front_paw
    - left_back_paw
    - right_back_paw
    - left_front_elbow
    - right_front_elbow

  minimal:
    - nose
    - neck_base
    - back_middle
    - tail_base
    - left_front_paw
    - right_front_paw
    - left_back_paw
