name: dlc_topviewmouse
num_joints: 27
num_channels: 2
coordinate_system: xy
center_joint: 9  # mouse_center
num_persons: 1

joint_names:
  - nose             # 0
  - left_ear         # 1
  - right_ear        # 2
  - left_ear_tip     # 3
  - right_ear_tip    # 4
  - left_eye         # 5
  - right_eye        # 6
  - neck             # 7
  - mid_back         # 8
  - mouse_center     # 9
  - mid_backend      # 10
  - mid_backend2     # 11
  - mid_backend3     # 12
  - tail_base        # 13
  - tail1            # 14
  - tail2            # 15
  - tail3            # 16
  - tail4            # 17
  - tail5            # 18
  - left_shoulder    # 19
  - left_midside     # 20
  - left_hip         # 21
  - right_shoulder   # 22
  - right_midside    # 23
  - right_hip        # 24
  - tail_end         # 25
  - head_midpoint    # 26

joint_parents: [26, 26, 26, 1, 2, 26, 26, 26, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 7, 19, 20, 7, 22, 23, 18, -1]

edges:
  - [26, 0]
  - [26, 1]
  - [26, 2]
  - [26, 5]
  - [26, 6]
  - [26, 7]
  - [1, 3]
  - [2, 4]
  - [7, 8]
  - [8, 9]
  - [9, 10]
  - [10, 11]
  - [11, 12]
  - [12, 13]
  - [13, 14]
  - [14, 15]
  - [15, 16]
  - [16, 17]
  - [17, 18]
  - [18, 25]
  - [7, 19]
  - [19, 20]
  - [20, 21]
  - [7, 22]
  - [22, 23]
  - [23, 24]

symmetric_pairs:
  - [1, 2]
  - [3, 4]
  - [5, 6]
  - [19, 22]
  - [20, 23]
  - [21, 24]

body_parts:
  head: [0, 1, 2, 3, 4, 5, 6, 26]
  spine: [7, 8, 9, 10, 11, 12]
  tail: [13, 14, 15, 16, 17, 18, 25]
  left_side: [19, 20, 21]
  right_side: [22, 23, 24]

# Keypoint presets for filtering
presets:
  standard:
    - nose
    - left_ear
    - right_ear
    - neck
    - mouse_center
    - left_shoulder
    - right_shoulder
    - left_hip
    - right_hip
    - tail_base
    - tail_end

  mars:
    - nose
    - left_ear
    - right_ear
    - neck
    - left_hip
    - right_hip
    - tail_base

  locomotion:
    - nose
    - neck
    - mouse_center
    - tail_base
    - tail_end

  minimal:
    - nose
    - mouse_center
    - tail_base
