name: mars_mouse
num_joints: 7
num_channels: 2
coordinate_system: xy
center_joint: 3
num_persons: 2

joint_names:
  - nose       # 0
  - left_ear   # 1
  - right_ear  # 2
  - neck       # 3
  - left_hip   # 4
  - right_hip  # 5
  - tail_base  # 6

joint_parents: [3, 3, 3, -1, 3, 3, 4]

edges:
  - [0, 3]
  - [1, 3]
  - [2, 3]
  - [3, 4]
  - [3, 5]
  - [4, 6]
  - [5, 6]

symmetric_pairs:
  - [1, 2]
  - [4, 5]

body_parts:
  head: [0, 1, 2, 3]
  body: [3, 4, 5]
  tail: [6]
