name: ntu_rgbd
num_joints: 25
num_channels: 3
coordinate_system: xyz
center_joint: 0
num_persons: 2

joint_names:
  - base_spine      # 0
  - mid_spine       # 1
  - neck            # 2
  - head            # 3
  - left_shoulder   # 4
  - left_elbow      # 5
  - left_wrist      # 6
  - left_hand       # 7
  - right_shoulder  # 8
  - right_elbow     # 9
  - right_wrist     # 10
  - right_hand      # 11
  - left_hip        # 12
  - left_knee       # 13
  - left_ankle      # 14
  - left_foot       # 15
  - right_hip       # 16
  - right_knee      # 17
  - right_ankle     # 18
  - right_foot      # 19
  - spine           # 20
  - left_thumb      # 21
  - left_tip        # 22
  - right_thumb     # 23
  - right_tip       # 24

joint_parents: [-1, 0, 20, 2, 20, 4, 5, 6, 20, 8, 9, 10, 0, 12, 13, 14, 0, 16, 17, 18, 1, 7, 7, 11, 11]

edges:
  - [0, 1]
  - [1, 20]
  - [20, 2]
  - [2, 3]
  - [20, 4]
  - [4, 5]
  - [5, 6]
  - [6, 7]
  - [7, 21]
  - [7, 22]
  - [20, 8]
  - [8, 9]
  - [9, 10]
  - [10, 11]
  - [11, 23]
  - [11, 24]
  - [0, 12]
  - [12, 13]
  - [13, 14]
  - [14, 15]
  - [0, 16]
  - [16, 17]
  - [17, 18]
  - [18, 19]

symmetric_pairs:
  - [4, 8]
  - [5, 9]
  - [6, 10]
  - [7, 11]
  - [12, 16]
  - [13, 17]
  - [14, 18]
  - [15, 19]
  - [21, 23]
  - [22, 24]

body_parts:
  torso: [0, 1, 2, 20]
  head: [2, 3]
  left_arm: [4, 5, 6, 7, 21, 22]
  right_arm: [8, 9, 10, 11, 23, 24]
  left_leg: [12, 13, 14, 15]
  right_leg: [16, 17, 18, 19]
