name: rat7m
num_joints: 20
num_channels: 3
coordinate_system: xyz
center_joint: 4
num_persons: 1

joint_names:
  - nose_tip
  - head_top
  - left_ear
  - right_ear
  - neck
  - left_shoulder
  - right_shoulder
  - left_elbow
  - right_elbow
  - left_wrist
  - right_wrist
  - spine_mid
  - left_hip
  - right_hip
  - left_knee
  - right_knee
  - left_ankle
  - right_ankle
  - tail_base
  - tail_mid

joint_parents: [4, 4, 4, 4, -1, 4, 4, 5, 6, 7, 8, 4, 11, 11, 12, 13, 14, 15, 11, 18]

edges:
  - [0, 4]
  - [1, 4]
  - [2, 4]
  - [3, 4]
  - [4, 5]
  - [4, 6]
  - [5, 7]
  - [6, 8]
  - [7, 9]
  - [8, 10]
  - [4, 11]
  - [11, 12]
  - [11, 13]
  - [12, 14]
  - [13, 15]
  - [14, 16]
  - [15, 17]
  - [11, 18]
  - [18, 19]

symmetric_pairs:
  - [2, 3]
  - [5, 6]
  - [7, 8]
  - [9, 10]
  - [12, 13]
  - [14, 15]
  - [16, 17]

body_parts:
  head: [0, 1, 2, 3]
  torso: [4, 5, 6, 11]
  left_arm: [5, 7, 9]
  right_arm: [6, 8, 10]
  left_leg: [12, 14, 16]
  right_leg: [13, 15, 17]
  tail: [18, 19]
