name: nw_ucla
num_joints: 20
num_channels: 3
coordinate_system: xyz
center_joint: 0
num_persons: 1

joint_names:
  - hip_center       # 0
  - spine            # 1
  - shoulder_center  # 2
  - head             # 3
  - left_shoulder    # 4
  - left_elbow       # 5
  - left_wrist       # 6
  - left_hand        # 7
  - right_shoulder   # 8
  - right_elbow      # 9
  - right_wrist      # 10
  - right_hand       # 11
  - left_hip         # 12
  - left_knee        # 13
  - left_ankle       # 14
  - left_foot        # 15
  - right_hip        # 16
  - right_knee       # 17
  - right_ankle      # 18
  - right_foot       # 19

joint_parents: [-1, 0, 1, 2, 2, 4, 5, 6, 2, 8, 9, 10, 0, 12, 13, 14, 0, 16, 17, 18]

edges:
  - [0, 1]
  - [1, 2]
  - [2, 3]
  - [2, 4]
  - [4, 5]
  - [5, 6]
  - [6, 7]
  - [2, 8]
  - [8, 9]
  - [9, 10]
  - [10, 11]
  - [0, 12]
  - [12, 13]
  - [13, 14]
  - [14, 15]
  - [0, 16]
  - [16, 17]
  - [17, 18]
  - [18, 19]

symmetric_pairs:
  - [4, 8]
  - [5, 9]
  - [6, 10]
  - [7, 11]
  - [12, 16]
  - [13, 17]
  - [14, 18]
  - [15, 19]

body_parts:
  torso: [0, 1, 2]
  head: [3]
  left_arm: [4, 5, 6, 7]
  right_arm: [8, 9, 10, 11]
  left_leg: [12, 13, 14, 15]
  right_leg: [16, 17, 18, 19]
